#version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE:      "${MYSQL_DATABASE}"
      MYSQL_USER:          "${MYSQL_USER}"
      MYSQL_PASSWORD:      "${MYSQL_PASSWORD}"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build:
      context: ./detailing-be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      EMAIL_USER:                     "${EMAIL_USER}"
      EMAIL_PASS:                     "${EMAIL_PASS}"
      SPRING_DATASOURCE_URL:          "${SPRING_DATASOURCE_URL}"
      SPRING_DATASOURCE_USERNAME:     "${SPRING_DATASOURCE_USERNAME}"
      SPRING_DATASOURCE_PASSWORD:     "${SPRING_DATASOURCE_PASSWORD}"
      SPRING_JPA_HIBERNATE_DDL_AUTO:  "${SPRING_JPA_HIBERNATE_DDL_AUTO}"
      SPRING_SQL_INIT_MODE:           "${SPRING_SQL_INIT_MODE}"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: ./detailing-fe
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: