frontend:
  url: http://localhost:3000/

backend:
  url: http://localhost:8080/

website:
  domain: localhost

auth0:
  domain: dev-vmtwqb6p6lr3if0d.us.auth0.com
  clientId: ${AUTH0_CLIENT_ID}
  clientSecret: ${AUTH0_CLIENT_SECRET}
  audience: https://highenddetailing/api
  issuer: https://dev-vmtwqb6p6lr3if0d.us.auth0.com/

okta:
  oauth2:
    issuer: https://dev-vmtwqb6p6lr3if0d.us.auth0.com/
    audience: https://highenddetailing/api

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/highenddetailing  # Changed from H2
    driver-class-name: com.mysql.cj.jdbc.Driver    # Changed from H2
    username: root                                 # Changed from 'sa'
    password: rootpassword                         # Added password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Changed dialect
#  auth0:
#    audience: https://highenddetailing/api

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://dev-vmtwqb6p6lr3if0d.us.auth0.com/
server:
  port: 8080